Epoch 1/15
2023-05-24 15:26:07.224725: I tensorflow/core/common_runtime/executor.cc:1210] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_0' with dtype int32
	 [[{{node Placeholder/_0}}]]
74/74 [==============================] - ETA: 0s - loss: 2.5199 - accuracy: 0.2142
2023-05-24 15:26:30.155216: I tensorflow/core/common_runtime/executor.cc:1210] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_0' with dtype int32
	 [[{{node Placeholder/_0}}]]
74/74 [==============================] - 23s 300ms/step - loss: 2.5199 - accuracy: 0.2142 - val_loss: 2.1941 - val_accuracy: 0.2400
Epoch 2/15
74/74 [==============================] - 21s 279ms/step - loss: 1.7750 - accuracy: 0.3702 - val_loss: 1.6612 - val_accuracy: 0.4000
Epoch 3/15
74/74 [==============================] - 22s 289ms/step - loss: 1.5496 - accuracy: 0.4382 - val_loss: 1.4438 - val_accuracy: 0.4200
Epoch 4/15
74/74 [==============================] - 22s 301ms/step - loss: 1.3584 - accuracy: 0.5152 - val_loss: 1.4108 - val_accuracy: 0.4600
Epoch 5/15
74/74 [==============================] - 25s 337ms/step - loss: 1.2798 - accuracy: 0.5434 - val_loss: 1.5187 - val_accuracy: 0.4200
Epoch 6/15
74/74 [==============================] - 23s 311ms/step - loss: 1.1642 - accuracy: 0.5917 - val_loss: 1.3285 - val_accuracy: 0.4800
Epoch 7/15
74/74 [==============================] - 24s 319ms/step - loss: 1.0985 - accuracy: 0.6212 - val_loss: 1.6212 - val_accuracy: 0.4600
Epoch 8/15
74/74 [==============================] - 24s 319ms/step - loss: 1.0671 - accuracy: 0.6280 - val_loss: 1.6977 - val_accuracy: 0.4600
Epoch 9/15
74/74 [==============================] - 24s 329ms/step - loss: 0.9534 - accuracy: 0.6597 - val_loss: 1.1787 - val_accuracy: 0.5600
Epoch 10/15
74/74 [==============================] - 24s 319ms/step - loss: 0.9602 - accuracy: 0.6759 - val_loss: 1.4179 - val_accuracy: 0.4800
Epoch 11/15
74/74 [==============================] - 24s 324ms/step - loss: 0.9053 - accuracy: 0.6746 - val_loss: 1.3726 - val_accuracy: 0.5200
Epoch 12/15
74/74 [==============================] - 24s 334ms/step - loss: 0.8454 - accuracy: 0.7029 - val_loss: 1.2280 - val_accuracy: 0.5800
Epoch 13/15
74/74 [==============================] - 25s 334ms/step - loss: 0.7919 - accuracy: 0.7388 - val_loss: 1.2781 - val_accuracy: 0.5200
Epoch 14/15
74/74 [==============================] - 25s 334ms/step - loss: 0.8004 - accuracy: 0.7221 - val_loss: 1.2431 - val_accuracy: 0.5000
Epoch 15/15
74/74 [==============================] - 24s 328ms/step - loss: 0.7460 - accuracy: 0.7499 - val_loss: 1.3103 - val_accuracy: 0.6000

2023-05-24 15:32:02.828524: I tensorflow/core/common_runtime/executor.cc:1210] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_0' with dtype int32
	 [[{{node Placeholder/_0}}]]
2/2 [==============================] - 0s 113ms/step - loss: 0.8980 - accuracy: 0.6400
[0.8980445861816406, 0.6399999856948853]
